export const FETCH_ROOMS = 'FETCH_ROOMS';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const INSERT_PRODUCT = 'INSERT_PRODUCT';
export const INSERT_TABLE = 'INSERT_TABLE';
//////////////////FOR TABLE///////////////////
export const FETCH_COUNT_TABLES = 'FETCH_COUNT_TABLES';
export const FETCH_INDEX_TABLES = 'FETCH_INDEX_TABLES';
export const SEARCH_PRODUCT = 'INSERT_PRODUCT';
export const FETCH_TABLES = 'FETCH_TABLES';
export const FETCH_STTTABLE = 'FETCH_STTTABLE';
export const ONCHANGE_TABLE = 'ONCHANGE_TABLE';
export const ONCHANGE_ROOM = 'ONCHANGE_ROOM';
export const ONCHANGE_STATUS = 'ONCHANGE_STATUS';
export const CHANGE_NAVIGATION = 'CHANGE_NAVIGATION';
export const CHANGE_TABLE_IDTABLE = 'CHANGE_TABLE_IDTABLE';
export const CHANGE_TABLE_NAME = 'CHANGE_TABLE_NAME';
export const CHANGE_TABLE_IDAREA = 'CHANGE_TABLE_IDAREA';
export const CHANGE_TABLE_STATUS = 'CHANGE_TABLE_STATUS';

///////////FOR MODAL///////////////
export const MODAL_HEADER_FOR_INSERT_UPDATE_TABLE = 'MODAL_HEADER_FOR_INSERT_UPDATE_TABLE';
export const MODAL_HEADER_FOR_ONTAP_TABLE = 'MODAL_HEADER_FOR_ONTAP_TABLE';
export const MODAL_HEADER_FOR_INSERT_UPDATE_ROOM = 'MODAL_HEADER_FOR_INSERT_UPDATE_ROOM';
export const MODAL_HEADER_FOR_ONTAP_ROOM = 'MODAL_HEADER_FOR_ONTAP_ROOM';

///////FOR FORM ROOM ////////////
export const CHANGE_ROOM_IDROOM = 'CHANGE_ROOM_IDROOM';
export const CHANGE_ROOM_NAMEROOM = 'CHANGE_ROOM_NAMEROOM';
export const CHANGE_ROOM_IDIDROOM = 'CHANGE_ROOM_IDIDROOM';
export const CHANGE_ROOM_NAME_SEARCH = 'CHANGE_ROOM_NAME_SEARCH';

///////FOR STATUS ///////
export const STATUS_EVENT_UPDATE_DELETE_INSERT = 'STATUS_EVENT_UPDATE_DELETE_INSERT';

//////STYLE EVENT ///////////
export const STATUS_STYLE_EVENT = 'STATUS_STYLE_EVENT';

///ONTAP//////////
export const ONTAP_CHANGE_ROOM = 'ONTAP_CHANGE_ROOM';
export const ONTAP_CHANGE_TABLE = 'ONTAP_CHANGE_TABLE';
export const ONTAP_CHANGE_BUTTON_TABLE = 'ONTAP_CHANGE_BUTTON_TABLE';
export const ONTAP_CHANGE_BUTTON_ROOM = 'ONTAP_CHANGE_BUTTON_ROOM';

/////////FORM ////////////

export const CHANGE_CUSTOMER_IDSUPPLIER = 'CHANGE_CUSTOMER_IDSUPPLIER';
export const CHANGE_CUSTOMER_NAMESUPPLIER = 'CHANGE_CUSTOMER_NAMESUPPLIER';
export const CHANGE_CUSTOMER_EMAILSUPPLIER = 'CHANGE_CUSTOMER_EMAILSUPPLIER';
export const CHANGE_CUSTOMER_PHONESUPPLIER = 'CHANGE_CUSTOMER_PHONESUPPLIER';
export const CHANGE_CUSTOMER_ADDRESSSUPPLIER = 'CHANGE_CUSTOMER_ADDRESSSUPPLIER';
export const CHANGE_CUSTOMER_NOTESUPPLIER = 'CHANGE_CUSTOMER_NOTESUPPLIER';
export const CHANGE_CUSTOMER_DEBITSUPPLIER = 'CHANGE_CUSTOMER_DEBITSUPPLIER';
export const CHANGE_CUSTOMER_AVATARSUPPLIER = 'CHANGE_CUSTOMER_AVATARSUPPLIER';
export const CHANGE_ID_NAME_SEARCH_SUPPLIER = 'CHANGE_ID_NAME_SEARCH_SUPPLIER';
export const CHANGE_DEBIT_SEARCH_SUPPLIER = 'CHANGE_DEBIT_SEARCH_SUPPLIER';

export const CHANGE_INDEX_SUPPLIER ='CHANGE_INDEX_SUPPLIER';

//CUSTOMER

export const CHANGE_IDCUSTOMER= 'CHANGE_IDCUSTOMER';
export const CHANGE_NAMECUSTOMER = 'CHANGE_NAMECUSTOMER';
export const CHANGE_EMAILCUSTOMER = 'CHANGE_EMAILCUSTOMER';
export const CHANGE_PHONECUSTOMER = 'CHANGE_PHONECUSTOMER';
export const CHANGE_ADDRESSCUSTOMER= 'CHANGE_ADDRESSCUSTOMER';
export const CHANGE_NOTECUSTOMER= 'CHANGE_NOTECUSTOMER';
export const CHANGE_DEBITCUSTOMER = 'CHANGE_DEBITCUSTOMER';
export const CHANGE_AVATARCUSTOMER = 'CHANGE_AVATARCUSTOMER';
export const CHANGE_BIRTHDAYCUSTOMER = 'CHANGE_BIRTHDAYCUSTOMER'
export const CHANGE_INDEX_CUSTOMER ='CHANGE_INDEX_CUSTOMER';
//*CUSTOMER */
export const CHANGE_ID_NAME_SEARCH_CUSTOMER = 'CHANGE_ID_NAME_SEARCH_CUSTOMER';
export const CHANGE_DEBIT_SEARCH_CUSTOMER = 'CHANGE_DEBIT_SEARCH_CUSTOMER';

////FETCH CUSTOMER ///////////

export const FETCH_COUNT_CUSTOMER = 'FETCH_COUNT_CUSTOMER';
export const FETCH_INDEX_CUSTOMER = 'FETCH_INDEX_CUSTOMER';
export const FETCH_CUSTOMER = 'FETCH_CUSTOMER';
export const CHANGE_NAVIGATION_CUSTOMER = 'CHANGE_NAVIGATION_CUSTOMER';

//////////REDIRECT///

export const CHECK_REDIRECT = 'CHECK_REDIRECT';
export const CHECK_LOADING = 'CHECK_LOADING';
export const CHECK_LOADING1 = 'CHECK_LOADING1';
export const REDIRECT_PAGES = 'REDIRECT_PAGES';

///////DASHBOARD////

// export const GET_TOTAL_REVENUE = 'GET_TOTAL_REVENUE';
// export const GET_COUNT_BILL = 'GET_COUNT_BILL';
// export const GET_COUNT_UNPAID_BILL  = 'GET_COUNT_UNPAID_BILL';
// export const GET_TOTAL_UNPAID_BILL = 'GET_TOTAL_UNPAID_BILL';
// export const GET_TOTAL_DEBIT_BILL = 'GET_TOTAL_DEBIT_BILL';
// export const GET_SUML_DEBIT_BILL = 'GET_SUM_DEBIT_BILL';
export const GET_STATISTICAL = 'GET_STATISTICAL';
export const GET_CHART = 'GET_CHART';
 //////ORDER//////
 export const GET_ORDER = 'GET_ORDER';

 //POS///
 export const GET_LIST_AREAS = 'GET_LIST_AREAS';
 export const GET_LIST_TABLES = 'GET_LIST_TABLES';
 export const GET_LIST_MENU = 'GET_LIST_MENU';
 export const GET_LIST_CATES = 'GET_LIST_CATES';
 export const GET_LIST_FEATURE_SEARCH_MENU = 'GET_LIST_FEATURE_SEARCH_MENU';
 export const FEATURE_APPENDMENU ='FEATURE_APPENDMENU';
 export const PAYMENT_TOTAL = 'PAYMENT_TOTAL';
 export const GUEST_MONEY = 'GUEST_MONEY';
 export const EXTRA_MONEY = 'EXTRA_MONEY';
 export const TAB_POS_CONTROLL = 'TAB_POS_CONTROLL';
 export const TABBACKGROUND_T_POS_CONTROLL = 'TABBACKGROUND_T_POS_CONTROLL';
 export const TABBACKGROUND_M_POS_CONTROLL = 'TABBACKGROUND_M_POS_CONTROLL';
export const SEARCH_CUSTOMER_POS = 'SEARCH_CUSTOMER_POS';
export const SHOW_CUSTOMER_POS = 'SHOW_CUSTOMER_POS';
export const SHOW_TABLE_POS = 'SHOW_TABLE_POS';
export const IDBILL_POS_DEFAULT = 'IDBILL_POS_DEFAULT';
export const GET_ID_USER = 'GET_ID_USER';
export const CONFIRM_POS = 'CONFIRM_POS';
export const GET_MENU = 'GET_MENU';
 
 
